### ISSUE TITLE
git submodule update fails

### ISSUE THREAD

**Issue by pmfurlong** [neuromorphs/CommonRoadMPC#2]
Issuing the command `git submodule update --init --recursive`  produces the error:
```
fatal: remote error: upload-pack: not our ref 32537b54aab50b6db0d68f7a47f9fddd8cb6928d
Fetched in submodule path 'SI_Toolkit', but it did not contain 32537b54aab50b6db0d68f7a47f9fddd8cb6928d. Direct fetching of that commit failed
```

Also, following the link to the particular SI_Toolkit commit, https://github.com/SensorsINI/SI_Toolkit/tree/32537b54aab50b6db0d68f7a47f9fddd8cb6928d does not seem to work.

**Comment by Florian-Bolli** [comment]
Seems like I didn't push the SI_toolkit commit, sorry
Should work now
otherwise please tell me

**Comment by Florian-Bolli** [comment]
make sure you pull again from master
I think I changed some function names in the SI toolkit
